import type { Metadata } from "next";
import "./globals.css";
import { neueRegrade, uncutSans } from "@/fonts/index";
import ThemeRegistry from "./ThemeRegistry";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${neueRegrade.className} ${uncutSans.className}`}>
        <ThemeRegistry options={{ key: 'mui' }}>
          {children}
        </ThemeRegistry>
      </body>
    </html>
  );
}
